version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Setup build environment
          command: |
            set -e
            export LANG=C
            source /home/vanilla/.nix-profile/etc/profile.d/nix.sh
            nix-shell --run "echo OK"
      - run:
          name: Build GHC
          command: |
            set -e
            export LANG=C
            source /home/vanilla/.nix-profile/etc/profile.d/nix.sh
            nix-build
