version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            nix-channel --update
      - run:
          name: Get source
          command: |
            git clone --recursive git://git.haskell.org/ghc.git
            cd ghc
            git checkout $(cat ../rev.txt)
            cd ..
      - restore_cache:
          keys:
            - nix-binary-cache-
      - run:
          name: Install dependencies
          command: |
            echo "binary-caches = file://${PWD}/binary-cache https://cache.nixos.org" >> /etc/nix/nix.conf
            drv=$(nix-instantiate)
            nix-store --include-outputs -qR $drv | grep -v $drv > deps.txt
            nix-store --realise $(cat deps.txt)
            mkdir -p binary-cache
            nix copy --to file://binary-cache $(cat deps.txt)
      - save_cache:
          key: nix-binary-cache-{{ epoch }}
          paths:
            - binary-cache
      - run:
          name: Build GHC
          command: |
            nix-build --cores 2 -A ghc-custom.all
      - run:
          name: Dump artifacts
          command: |
            mkdir dist-cache
            nix copy --to file://dist-cache/ $(readlink result) $(readlink result-doc)
      - store_artifacts:
          path: dist-cache
          destination: dist-cache
