version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-nix-store-dump-
      - run:
          name: Prepare build
          command: |
            nix-env -iA nixpkgs.xz
            [[ -f store-dump ]] && nix-store --import < store-dump
            drv=$(nix-instantiate)
            echo Building $drv
            nix-store --query --references $drv > deps.txt
            nix-store --realise $(cat deps.txt) > bin-deps.txt
            nix-store --export $(nix-store -qR $(cat bin-deps.txt)) > store-dump

      - save_cache:
          key: v4-nix-store-dump-{{ epoch }}
          paths:
            - store-dump
      - run:
          name: Build GHC
          command: |
            nix-build --cores 2 -A ghc-custom.all
      - run:
          name: Dump artifacts
          command: |
            mkdir dist-cache
            nix copy --to file://dist-cache/ $(readlink result) $(readlink result-doc)

      - store_artifacts:
          path: dist-cache
          destination: dist-cache
