version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install nix
          command: |
            set -e
            apt update
            apt install -y curl
            curl https://nixos.org/nix/install > install-nix.sh
            sha256sum -c <<<"1b64d89db0bf4d6ddb36a7a9fff4b19dd96b93a65af6b245563689aba4134b77  install-nix.sh"
            bash install-nix.sh
