version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-nix-store-dump-
      - run:
          name: Prepare build
          no_output_timeout: 30m
          command: |
            nix-env -iA nixpkgs.xz
            [[ -f store-dump ]] && nix-store --import < store-dump
            drv=$(nix-instantiate)
            echo Building $drv
            nix-store --query --references $drv > deps.txt
            nix-store --realise $(cat deps.txt) > bin-deps.txt
            nix-store --export $(nix-store -qR $(cat bin-deps.txt)) > store-dump

      - save_cache:
          key: v4-nix-store-dump-{{ epoch }}
          paths:
            - store-dump
      - run:
          name: Build GHC
          no_output_timeout: 1h
          command: |
            nix-build --cores 2 -A ghc-custom.all > output.txt

      - run:
          name: Upload to cachix
          command: |
            nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/1d4de0d552ae9aa66a5b8dee5fb0650a4372d148
            cachix push $CACHIX_NAME < output.txt
