version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-nix-store-dump-
      - run:
          name: Prepare build
          command: |
            nix-env -iA nixpkgs.xz
            mkdir -p store-dump
            find store-dump/ | tail -n +2 | xargs -I name -- sh -c 'nix-store --import < name'
            drv=$(nix-instantiate)
            echo Building $drv
            nix-store -qR $drv | grep '.drv$' | grep -v $drv > deps.txt
            nix-store --realise $(cat deps.txt) > bin-deps.txt
            sed -e 's|/nix/store/||' bin-deps.txt | xargs -I name -- sh -c 'nix-store --export name > store-dump/name'
      - save_cache:
          key: v3-nix-store-dump-{{ epoch }}
          paths:
            - store-dump
      - run:
          name: Build GHC
          command: |
            nix-build --cores 2 -A ghc-custom.all
      - run:
          name: Dump artifacts
          command: |
            mkdir dist-cache
            nix copy --to file://dist-cache/ $(readlink result) $(readlink result-doc)
      - store_artifacts:
          path: dist-cache
          destination: dist-cache
