version: 2
jobs:
build:
docker:
    - image: terrorjack/vanilla:circleci
steps:
    - checkout
    - run:
        name: Clone submodules
        command: |
            git submodule sync --recursive
            git submodule update --recursive --init
    - run:
        name: Parse version
        command: |
            echo $(grep '^AC_INIT' ghc/configure.ac | cut -d[ -f3 | cut -d] -f1)$(date +'.%Y%m%d') > version.txt
            echo Building GHC as version: $(cat version.txt)
    - run:
        name: Setup build environment
        command: |
            set -e
            export LANG=C
            source /home/vanilla/.nix-profile/etc/profile.d/nix.sh
            nix-shell --argstr version $(cat version.txt) --run "echo OK"
    - run:
        name: Build GHC
        command: |
            set -e
            export LANG=C
            source /home/vanilla/.nix-profile/etc/profile.d/nix.sh
            nix-build --argstr version $(cat version.txt)
