version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout

      - run:
          name: Build GHC
          no_output_timeout: 1h
          command: |
            nix-env -iA nixpkgs.xz
            nix-build --cores 2 -A ghc-custom.all > output.txt

      - run:
          name: Upload to cachix
          command: |
            nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/1d4de0d552ae9aa66a5b8dee5fb0650a4372d148
            cachix push $CACHIX_NAME < output.txt
