version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Clone submodules
                command: |
                    git submodule sync --recursive
                    git submodule update --recursive --init
            - run:
                name: Install Nix
                command: |
                    export LANG=C
                    export USER=`whoami`

                    curl https://nixos.org/nix/install > install-nix.sh
                    sha256sum -c <<<"1b64d89db0bf4d6ddb36a7a9fff4b19dd96b93a65af6b245563689aba4134b77  install-nix.sh"
                    bash install-nix.sh

                    echo 'export LANG=C' >> ~/env.sh
                    echo 'export USER=`whoami`' >> ~/env.sh
                    echo "unset NIX_PATH" >> ~/env.sh
                    echo "export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/env.sh
                    echo "source ~/.nix-profile/etc/profile.d/nix.sh" >> ~/env.sh
            - run:
                name: Basic setup
                command: |
                    source ~/env.sh
                    nix-env -i bash
            - run:
                name: Parse version
                command: |
                    source ~/env.sh
                    echo $(grep '^AC_INIT' ghc/configure.ac | cut -d[ -f3 | cut -d] -f1)$(date +'.%Y%m%d') > version.txt
                    echo Building GHC as version: $(cat version.txt)
            - run:
                name: Setup build environment
                command: |
                    source ~/env.sh
                    nix-shell --argstr version $(cat version.txt) --run "echo OK"
            - run:
                name: Build GHC
                command: |
                    source ~/env.sh
                    nix-build --argstr version $(cat version.txt) -A ghc.all
            - run:
                name: Dump artifact
                command: |
                    source ~/env.sh
                    mkdir dump
                    nix-push --dest dump result result-doc
                    mkdir artifacts
                    tar -cJf artifacts/cache.tar.xz dump/
            - store_artifacts:
                path: ./artifacts

