version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:circleci
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            nix-channel --update
      - run:
          name: Get source
          command: |
            git clone --recursive git://git.haskell.org/ghc.git
            cd ghc
            git checkout $(cat ../rev.txt)
            cd ..
      - run:
          name: Build GHC
          command: |
            nix-build --cores 2 -A ghc-custom.all
      - run:
          name: Dump binary cache
          command: |
            mkdir cache
            nix copy --to file://cache/ result result-doc
      - store_artifacts:
          path: cache
          destination: cache

