version: 2
jobs:
    build:
        docker:
            - image: terrorjack/vanilla:circleci
        steps:
            - checkout
            - run:
                name: Clone submodules
                command: |
                    git submodule sync --recursive
                    git submodule update --recursive --init
            - run:
                name: export LANG=C
                command: |
                    echo 'export LANG=C' >> ~/.profile
            - run:
                name: Basic setup
                command: |
                    nix-env -i bash
            - run:
                name: Parse version
                command: |
                    echo $(grep '^AC_INIT' ghc/configure.ac | cut -d[ -f3 | cut -d] -f1)$(date +'.%Y%m%d') > version.txt
                    echo Building GHC as version: $(cat version.txt)
            - run:
                name: Setup build environment
                command: |
                    nix-shell --argstr version $(cat version.txt) --run "echo OK"
            - run:
                name: Build GHC
                command: |
                    nix-build --argstr version $(cat version.txt)
